# Streamlit Secrets Template
# Copy this to .streamlit/secrets.toml for API keys

# Google Gemini API Key (optional - for enhanced AI analysis)
GEMINI_API_KEY = "your-gemini-api-key-here"

# Note: The app works without this key, but AI analysis will be basic